# Generated by Django 4.1.6 on 2023-05-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_book_category_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A detailed description of the book.', null=True)),
                ('publisher', models.CharField(help_text='The publisher of the book.', max_length=100, null=True)),
                ('pages', models.IntegerField(help_text='The number of pages in the book.', null=True)),
                ('publish_date', models.DateField(help_text='The publication date of the book.', null=True)),
                ('language', models.CharField(help_text='The language of the book.', max_length=50, null=True)),
                ('book_type', models.CharField(help_text='The type of the book.', max_length=50, null=True)),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='base.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='details',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='book_info', to='base.bookdetails'),
            preserve_default=False,
        ),
    ]
