# Generated by Django 4.1.6 on 2023-05-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_bookdetails_book_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='details',
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
    ]
