# Generated by Django 4.1.6 on 2023-05-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_book_details_alter_bookdetails_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
    ]
