# Generated by Django 4.1.6 on 2023-05-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_bookdetails_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='details',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='base.bookdetails'),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_details_relation', to='base.book'),
        ),
    ]
