# Generated by Django 4.1.6 on 2023-05-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_book_details_alter_bookdetails_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookdetails'),
        ),
    ]
