# Generated by Django 4.1.6 on 2023-05-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_bookdetails_book_alter_bookdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
