# Generated by Django 4.1.6 on 2023-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_bookdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
