# Generated by Django 4.1.6 on 2023-05-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_delete_bookdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A detailed description of the book.', null=True)),
                ('publisher', models.CharField(help_text='The publisher of the book.', max_length=100, null=True)),
                ('pages', models.IntegerField(help_text='The number of pages in the book.', null=True)),
                ('publish_date', models.DateField(help_text='The publication date of the book.', null=True)),
                ('language', models.CharField(help_text='The language of the book.', max_length=50, null=True)),
                ('book_type', models.CharField(help_text='The type of the book.', max_length=50, null=True)),
            ],
        ),
    ]
