# Generated by Django 4.1.6 on 2023-05-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_book_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bookdetails'),
        ),
    ]
