# Generated by Django 4.1.6 on 2023-05-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_book_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='details',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(help_text='The type of the book.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='A detailed description of the book.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(help_text='The language of the book.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(help_text='The number of pages in the book.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(help_text='The publication date of the book.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='The publisher of the book.', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
