# Generated by Django 4.1.6 on 2023-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_book_details_book_book_type_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog', max_length=70)),
                ('date', models.DateField(auto_now_add=True)),
                ('publisher', models.CharField(help_text='The publisher of the blog', max_length=100, null=True)),
                ('description', models.TextField(help_text='A description of the blog', null=True)),
                ('image', models.ImageField(upload_to='blogs/')),
            ],
        ),
    ]
